# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CapitalOneSES-August2019Submit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CapitalOneSES-August2019Submit
  pod 'Google-Mobile-Ads-SDK'

end
